pubName: tba_api_dart_dio_client
pubVersion: 0.0.2
pubDescription: "The Blue Alliance API Dart Dio SDK"
pubAuthor: Jack1221
pubAuthorEmail: iambent.omnishambles@gmail.com
pubHomepage: https://github.com/jr1221/tba_api_dart_dio_client
